export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  FACILITY_NOT_FOUND: "FACILITY_NOT_FOUND",
  FACILITY_ALREADY_LOCKED: "FACILITY_ALREADY_LOCKED",
  LOCKDOWN_NOT_FOUND: "LOCKDOWN_NOT_FOUND",
  LOCKDOWN_ALREADY_RELEASED: "LOCKDOWN_ALREADY_RELEASED",
  LOCKDOWN_REPLAYED: "LOCKDOWN_REPLAYED",
  ROUTE_DISPATCH_FORBIDDEN: "ROUTE_DISPATCH_FORBIDDEN"
} as const;
